services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    environment:
      - DATABASE_URL=mongodb://mongo:27017/empDirectoryApp
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    environment:
      - NEXT_PUBLIC_GRAPHQL_ENDPOINT=http://backend:8000/graphql
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data: 